In [1]:
import pandas as pd

In [2]:
dataset = pd.read_excel(r"C:\Users\rajsi\Downloads\Blood-Report-Analysis-main\Blood-Report-Analysis-main\Copy of dataset.xlsx")

In [3]:
dataset.head()

Gender  Age        HGB  Thrombocytes  leukocytes  Neutrophil  Eosinophil  \
0       1   14  11.741403      2.797451    7.293167          48           3   
1       1   17  11.780947      3.325040    5.029948          53           3   
2       1    8  11.659685      1.810470    9.106578          50           5   
3       1    8  12.066457      1.831865    5.376189          54           1   
4       1   10  11.522367      3.987018    9.990269          44           1   

   Basophil  Lymphocyte  Monocyte  class  
0         1          30         3      1  
1         0          25         9      1  
2         0          20         6      1  
3         1          23         2      1  
4         1          26         9      1

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [5]:
X = dataset.drop("class",axis=1)
y = dataset['class']

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.3, random_state=20)

In [7]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((3150, 10), (1350, 10), (3150,), (1350,))

In [8]:
y

0        1
1        1
2        1
3        1
4        1
        ..
4495    15
4496    15
4497    15
4498    15
4499    15
Name: class, Length: 4500, dtype: int64

In [9]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np


In [10]:
models = {
    "SVC": SVC(kernel='linear'),
    "RandomForest": RandomForestClassifier(n_estimators=100, random_state=42),
    'GradientBoosting': GradientBoostingClassifier(n_estimators=100, random_state=42),
    "KNeighbors": KNeighborsClassifier(n_neighbors=5),
    "MultinomialNB": MultinomialNB()
}

for model_name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    accuracy = accuracy_score(y_test, predictions)

    cm = confusion_matrix(y_test, predictions)

    print(f"{model_name} accuracy: {accuracy}")
    print(f"{model_name} Confusion Matrix:")
    print(np.array2string(cm, separator=''))


SVC accuracy: 0.9859259259259259
SVC Confusion Matrix:
[[90 0 0 0 0 1 0 0 0 0 0 0 0 1 0]
 [ 092 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [ 0 296 4 0 0 0 0 0 0 0 0 0 0 0]
 [ 0 0 098 0 0 0 0 0 0 0 0 0 0 0]
 [ 0 0 0 096 0 0 0 0 0 0 0 0 0 0]
 [ 0 0 0 0 083 0 0 0 0 0 0 0 0 0]
 [ 0 0 0 0 0 090 3 0 0 0 0 0 0 0]
 [ 0 0 0 0 0 0 580 0 0 0 0 0 0 0]
 [ 0 0 0 0 0 0 0 097 0 0 0 0 0 0]
 [ 0 0 0 0 0 0 0 0 090 0 0 0 0 0]
 [ 0 0 0 0 0 0 0 0 0 086 0 0 0 0]
 [ 0 0 0 0 0 0 0 0 0 0 071 0 0 0]
 [ 0 0 0 0 0 0 0 0 0 0 0 086 0 0]
 [ 0 1 0 0 0 0 0 0 0 0 0 0 090 0]
 [ 0 0 0 0 0 0 2 0 0 0 0 0 0 086]]
RandomForest accuracy: 1.0
RandomForest Confusion Matrix:
[[ 92  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [  0 92  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [  0  0102  0  0  0  0  0  0  0  0  0  0  0  0]
 [  0  0  0 98  0  0  0  0  0  0  0  0  0  0  0]
 [  0  0  0  0 96  0  0  0  0  0  0  0  0  0  0]
 [  0  0  0  0  0 83  0  0  0  0  0  0  0  0  0]
 [  0  0  0  0  0  0 93  0  0  0  0  0  0  0  0]
 [  0  0  0  0  0  0  0 85  0  0 

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Create a RandomForestClassifier instance
rfc = RandomForestClassifier()

# Train the model
rfc.fit(X_train, y_train)

# Make predictions
ypred = rfc.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, ypred)
print("Accuracy:", accuracy)


Accuracy: 1.0


In [14]:
import pickle 
pickle.dump(rfc,open("rfc.pkl",'wb'))

In [15]:
rfc = pickle.load(open(r"C:\Users\rajsi\Downloads\rfc.pkl",'rb'))

In [16]:
rfc.predict(X_test.iloc[10].values.reshape(1,-1))

C:\Users\rajsi\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([14], dtype=int64)